import type { Metadata } from "next";
import "./globals.css";
import Head from 'next/head';
import ClientBody from "./ClientBody";

export const metadata: Metadata = {
  title: "Biomax",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <Head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&display=swap"
        />
        <style>{`
          @font-face {
            font-family: 'Roboto';
            font-style: normal;
            font-weight: 400;
            src: url('/fonts/roboto-regular-webfont.woff2') format('woff2');
          }
          @font-face {
            font-family: 'Roboto';
            font-style: normal;
            font-weight: 500;
            src: url('/fonts/roboto-medium-webfont.woff2') format('woff2');
          }
        `}</style>
      </Head>
      <body
        style={{
          fontFamily: 'Roboto, Arial, sans-serif',
          background: '#f4f5f5',
          margin: 0,
        }}
        suppressHydrationWarning
        className="antialiased"
      >
        <ClientBody>{children}</ClientBody>
      </body>
    </html>
  );
}
